services:

  web:
    build:
      context: ./app
    volumes:
      - type: bind
        target: /app
        source: ./app
      - ./app:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/medias
    ports:
      - "8000:8000"
    env_file: ./.env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DEBUG: "True"
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: "*"

  notification_system:
    image: quay.io/soketi/soketi:1.4-16-debian
    ports:
      - 6001:6001
      - 9601:9601
    environment:
      - SOKETI_DEBUG=1
    command:
      - soketi start --config=/socketi/config.json
    volumes:
      - ./socketi/config.json:/socketi/config.json


  cartographie:
    build:
      context: ./static
    volumes:
      - ./static:/app
      - static_volume:/app/static/assets
    ports:
      - "9000:9000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DEBUG=True
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS="*"


volumes:
  postgres_data:
  static_volume:
  media_volume:
